맛집 데이터 크롤링 기본 세팅
techeer-f5/jmt-monster-backend pull request #20
Opened 2022-04-15 18:37 UTC by Yong-ga-ri

- 하나의 맛집 크롤링에 대한 컨트롤러만 만들었습니다

추후 크롤링 작업이 완료되면 구체적인 작업을 추가할 예정입니다.

### 이슈
- 많은 맛집에 대한 크롤링을 어떻게 처리할 것인가
- 맛집에 대한 도메인과 크롤링에 대한 도메인을 나눈다면 엔티티는 어디에 정의해야 하는가?
    - 우선은 크롤링한 데이터가 바로 저장되기를 바라며 크롤링 도메인에 정의했습니다.

2022-04-15 19:14 UTC, DPS0340 requested changes
* `getMenuByRestId`는 REST 의미상 `@GetMapping`으로 전환 부탁드려요!
* 여러개의 메뉴를 반환해야 할 텐데, `List<CrawlingResponseDto>`로 전환 부탁드립니다! `@RestController` 어노테이션을 사용하셨으니 `ResponseEntity`로 명세 안하셔도 자동으로 래핑이 되어요!
* 제 개인적인 의견입니다만 다른 모든 클래스들은 맛집 도메인으로 네이밍하고, 서비스만 크롤링 로직이 담기는 클래스는 `MenuCrawlingService`라고 네이밍하시면 될 것 같아요! 패키지는 분리하지 않고 맛집으로 일원화하는것이 좋을 듯 합니다..!

2022-04-15 19:16 UTC, DPS0340 commented
서비스는 간단하게 컨트롤러가 사용하는 비즈니스 로직이 들어있는 메소드의 클래스라고 보시면 돼요!

조금 더 깊게 이해하시려면, 구글 혹은 도메인 주도 설계 - 에릭 에반스 추천드립니다 ㅎㅎ

2022-04-16 03:54 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/controller/CrawlingController.java
> +    public
이 부분 때문에 merge하면 컴파일 오류 날 것 같습니다! 작업 완료 후 PR 부탁드려요!

2022-04-16 03:55 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/controller/CrawlingController.java
> +    public
앗 잘못 봤네요 ㅎㅎ

2022-04-16 04:00 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private Long id;
ID 타입은 제가 #12 ([참고](https://github.com/techeer-f5/jmt-monster-backend/pull/12#discussion_r846816602)) 에서도 같은 comment를 남겼는데, 특별한 사유가 없다면 타입은 UUID로 통일하면 좋을 것 같아요!

2022-04-16 04:03 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private String price; // 가격
가격을 String 타입으로 지정하신 이유가 있나요? 화폐에는 실수 표현과 정확도 때문에 `BigDecimal` 등을 사용하곤 합니다!

2022-04-16 04:06 UTC, litsynp requested changes
Comment 확인 부탁드립니다! :)

- ID (PK) 타입
- 가격 타입

2022-04-16 04:09 UTC, litsynp commented
이슈 관련해서,

- 맛집에 대한 도메인과 크롤링에 대한 도메인을 나눈다면 엔티티는 어디에 정의해야 하는가?

저도 크롤링 기능이 맛집 관련이니 @DPS0340 의견에 동의합니다! 추후에 뭔가 의미가 맞지 않는다 판단되면 패키지를 분리해도 될 것 같아요.

2022-04-16 06:47 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private String price; // 가격
해당 타입이 있는지 몰랐네요! 플랫폼마다 크롤링 한 데이터에서 [10,000원], [10,000] 등 여러가지 형태를 써서 우선 저장만을 위해 저렇게 지정했습니다

2022-04-16 06:49 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private Long id;
네 확인했습니다 :)

2022-04-16 06:52 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private String price; // 가격
넵! 크롤링한 데이터를 바로 넣지 않고 한번 정제 작업을 거친 뒤에 넣는게 좋을 것 같습니다 👍

2022-04-16 06:56 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/controller/CrawlingController.java
> +    public
넵 또 문제있으면 말씀해주세요 감사합니다 👍

2022-04-16 06:58 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/crawling/entity/Menu.java
> +    private String price; // 가격
넵 이해했습니다! 그러면 BigDecimal로 바꿔볼게요 😄

2022-04-16 07:01 UTC, Yong-ga-ri commented
@DPS0340 님!

`getMenuByRestId`는 REST 의미상 `@GetMapping`으로 전환 부탁드려요!

이 부분이 컨트롤러 부분 말씀하신게 맞을까요? 메소드 네이밍과 어노테이션 중 어떤 부분을 말씀하신건가요? 
제가 자바 프로젝트가 처음이라 이해도가 많이 떨어지네요 😂

2022-04-16 10:00 UTC, DPS0340 commented
> @DPS0340 님!
> 
> `getMenuByRestId`는 REST 의미상 `@GetMapping`으로 전환 부탁드려요!
> 
> 이 부분이 컨트롤러 부분 말씀하신게 맞을까요? 메소드 네이밍과 어노테이션 중 어떤 부분을 말씀하신건가요? 제가 자바 프로젝트가 처음이라 이해도가 많이 떨어지네요 😂

컨트롤러 메소드 어노테이션 맞습니다 ㅎㅎㅎㅎㅎ

2022-05-18 14:54 UTC, closed without merging