Review API Test Code
techeer-f5/jmt-monster-backend pull request #50
Opened 2022-05-13 16:19 UTC by Sith-call

## DONE
* Domain Test Code
* Repository Test Code

## TODO
* Service Test Code
* Controller Test Code

## COMMENT
* H2:1.4.200 -> H2:1.4.196
* 1.4.200에서 Hibernate ORM 오류가 발생하여, Repository Unit Test가 불가능. 따라서 변경
* [H2 1.4.200 Issue](https://github.com/h2database/h2database/issues/3325)

2022-05-16 20:32 UTC, DPS0340 requested changes

2022-05-16 20:32 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImageTest.java
> +        givenReviewImage.update("Changed URL");
엔티티를 업데이트한 뒤, 레포지토리 메소드를 사용해서 다시 엔티티를 가져와야 영속성 컨텍스트를 넘어서 데이터베이스단까지 제대로 동작했는가를 알 수 있을 것 같습니다.
똑같은 패턴을 사용하고 있는 다른 테스트 코드들도 마찬가지일 것 같습니다.

2022-05-18 12:12 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImageTest.java
> +        givenReviewImage.update("Changed URL");
넵 알겠습니다~! 
좋은 지적이네요

2022-05-21 14:34 UTC, himJJong reviewed
코드 리뷰가 늦었네요 죄송합니다! 고생 많으셨어요!! :)

2022-05-21 14:34 UTC, himJJong commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRequestRepositoryTest.java
> +package com.techeer.f5.jmtmonster.domain.review.dao;
혹시 우석님이 작성하신 테스트 코드 흐름을 알 수 있을까요? 그리고 테스트 코드에 대한 결과는 어떤식으로 검증되는지 궁금합니다!!

2022-05-23 04:10 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRequestRepositoryTest.java
> +package com.techeer.f5.jmtmonster.domain.review.dao;
test code는 given when then 스타일에 따라서 작성하였습니다. 이 스타일 안에 코드 흐름 및 결과 입증 방식이 담겨 있습니다. 제가 여기서 자세히 설명하기 힘들어서 제가 쓴 벨로그 글 링크 첨부하겠습니다~ 

https://velog.io/@chldntjr0425/%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C

2022-05-23 04:14 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImageTest.java
> +        givenReviewImage.update("Changed URL");
코드를 다시 보니 해당 코드는 domain 클래스에 있는 메소드라 레포지토리 테스트는 굳이 진행하지 않아도 될 것 같습니다.

2022-05-23 15:22 UTC, himJJong commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/dao/ReviewRequestRepositoryTest.java
> +package com.techeer.f5.jmtmonster.domain.review.dao;
자세하게 나와있네요 ㅎㅎ 링크 감사합니다!!

2022-05-25 11:36 UTC, closed without merging