카카오 지도 API, 맛집 데이터 수집
techeer-f5/jmt-monster-backend pull request #75
Opened 2022-06-30 00:39 UTC by himJJong

## DONE

- Controller와 Service 로직 분리
- 메뉴 정보 String형태에 Dto 사용
- 맛집 좌표 값 삭제

2022-07-01 00:22 UTC, Yong-ga-ri approved these changes

2022-07-01 04:59 UTC, Sith-call approved these changes
repository 대신에 information을 따로 만들어서 쓴게 인상적이네요! 수고하셨습니다~

2022-07-01 17:25 UTC, DPS0340 requested changes
코드 리뷰 올려드립니다.

2022-07-01 17:29 UTC, DPS0340 requested changes
코드 리뷰 2차 올려드립니다.

2022-07-01 17:29 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/RestaurantInfo.java
> +package com.techeer.f5.jmtmonster.domain.restaurant.service.information;
위와 동일 내용입니다.

2022-07-01 17:35 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
>          RestTemplate restTemplate = new RestTemplate();
RestaurantMapper와 RestTemplate는 DI가 유용할 것 같습니다. Bean으로 만들어 보실까요?

2022-07-02 06:37 UTC, himJJong commented on src/main/resources/META-INF/menu-format.json
> +//맛집 메뉴 정보 조회
넵 알겠습니다. 주말내에 정정하겠습니다!

2022-07-02 06:38 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +    public MenuInfoResponseDto getMenuByKakao(@PathVariable("cidnum") long cidnum) {
아하 컨트롤러 어노테이션이면 서비스에서 제거하는게 일반적이군요 코드에 반영하겠습니다.

2022-07-02 06:38 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/MenuInfo.java
> +package com.techeer.f5.jmtmonster.domain.restaurant.service.information;
확인했습니다 좋은지적 감사드립니다!

2022-07-02 06:39 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
>          RestTemplate restTemplate = new RestTemplate();
오호 Bean으로 하는것도 한번 알아본 후 가능하다면 빠른 시일내에 적용하겠습니다. 지적감사드립니다!! :)

2022-07-02 12:06 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +//        RestaurantInfo restaurantInfo = new RestaurantInfo(cid, restaurantName);
이 부분은 형식의 데이터를 가저오는게 좋을지 몰라서 남겨두었습니다!

2022-07-02 12:07 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +//                .y_cord(restaurant.getY_cord())
지난번에 데이터베이스에 `위치 좌표정도는 저장하는게 낫다`, `그냥 조회할 때마다 데이터를 요청하는게 낫다`라는 두 의견이 있어서 혹시 몰라 `RestaurantMapper.java`파일을 삭제하지 않았습니다

2022-07-02 12:08 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/MenuInfo.java
> +package com.techeer.f5.jmtmonster.domain.restaurant.service.information;
네 이 부분은 고민을 많이 했는데 그렇게 정정하겠습니다!

2022-07-03 05:19 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +//        RestaurantInfo restaurantInfo = new RestaurantInfo(cid, restaurantName);
데이터 형식을 한 가지로 결정했습니다.  
말씀하신 부분은 삭제하도록 하겠습니!

2022-07-03 05:22 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +//                .y_cord(restaurant.getY_cord())
이 부분에 대해서 기획이 확실하지 않은거로 기억합니다! 가장 마지막으로 했던 얘기가 `데이터베이스에 저장을 하지 않고 필요할 때마다 요청받자`라고 했던거로 기억하여 지우도록 하겠습니다!

2022-07-03 06:23 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +//        RestaurantInfo restaurantInfo = new RestaurantInfo(cid, restaurantName);
제가 설명이 부족했네요 ㅜㅜ
이전의 코드를 확인하실 때는 git의 로그로 확인해보시면 좋을 것 같습니다~

2022-07-03 13:22 UTC, litsynp requested changes
고생하셨습니다! 리뷰 확인 부탁드립니다 🙂

전체적으로 봤을 때, 변수 및 메서드 네이밍, 사용되지 않는 코드 제거에 신경써주시면 좋을 것 같습니다!

추가로 `restaurant` 패키지 내용을 확인했는데 패키지 양식이 [맛집 몬스터 패키지 양식](https://www.notion.so/litsynp/a92e72285aa04090a631e04eed40d8a0)과 상이한 것 같아 다음과 같이 변경되어야 할 것 같아서 알려드립니다!

- `controller`
- `dto`
- `entity` -> `domain`
- `repository` -> `dao`
- `service`

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/response/MenuInfoResponseDto.java
> +    private List menuList;
Raw type의 제네릭은 권장되지 않는 방식입니다.

https://github.com/techeer-f5/jmt-monster-backend/pull/45#discussion_r872116291 에서 언급된 내용입니다.

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +//                .y_cord(restaurant.getY_cord())
추가로, 변수명을 `x_cord`, `y_cord`가 아닌 [camelCase](https://blog.naver.com/ege1001/220466932974)로 지정해주시면 더 좋을 것 같습니다.
Restaurant entity (`Restaurant.java`) 도 마찬가지로 적용 부탁드립니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/controller/RestaurantController.java
> +        MenuInfoResponseDto menuInfoResponseDto = menuService.getMenuByKakao(cid);
API endpoint는 `/restaurants` 인데 왜 `getMenuByKakao`로 네이밍하셨는지 궁금합니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/response/RestaurantResponseDto.java
> +    private List menuList;
동일한 내용입니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/MenuInfo.java
> +    private List menuList;
동일한 내용입니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/MenuInfo.java
> +public class MenuInfo {
`MenuInfo`의 용도가 무엇인지 클래스의 이름만 가지고는 판단하기가 어려운 것 같습니다.
클래스의 이름을 좀 더 알아보기 쉽고 일관성 있게 작성해주시고, 어렵다면 주석을 달아주시면 좋을 것 같습니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/RestaurantInfo.java
> +public class RestaurantInfo {
`RestaurantInfo`의 용도가 무엇인지 클래스의 이름만 가지고는 판단하기가 어려운 것 같습니다.
클래스의 이름을 좀 더 알아보기 쉽고 일관성 있게 작성해주시고, 어렵다면 주석을 달아주시면 좋을 것 같습니다!

2022-07-03 13:22 UTC, litsynp commented on src/main/resources/application-secret.yml
> -# Local settings
이 부분이 수정된 이유가 있을까요?

2022-07-03 14:10 UTC, DPS0340 approved these changes
저는 좋은 듯 하여 Approve 합니다!
고생 많으셨습니다!! 👍 👍 👍 👍 👍

2022-07-03 14:12 UTC, DPS0340 commented
> 추가로 `restaurant` 패키지 내용을 확인했는데 패키지 양식이 [맛집 몬스터 패키지 양식](https://www.notion.so/litsynp/a92e72285aa04090a631e04eed40d8a0)과 상이한 것 같아 다음과 같이 변경되어야 할 것 같아서 알려드립니다!
> 
> * `controller`
> * `dto`
> * `entity` -> `domain`
> * `repository` -> `dao`
> * `service`

@litsynp 앗 저... `domain`보다는 `entity`를 선호하고 `dao`보다는 `repository`를 선호하는데 이 점에 대해서 수요일 미팅 즈음에 논의해주시면 감사하겠습니다!

2022-07-03 23:32 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/response/MenuInfoResponseDto.java
> +    private List menuList;
확인했습니다!

2022-07-03 23:38 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/controller/RestaurantController.java
> +        MenuInfoResponseDto menuInfoResponseDto = menuService.getMenuByKakao(cid);
음 팀원분들이 알기 쉽게 이름 쓴다는 생각에 그렇게 적용했는데 생각해보니 잘못된거 같습니다. 정정하겠습니다!

2022-07-03 23:39 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/information/MenuInfo.java
> +public class MenuInfo {
확인했습니다 알아보기 쉽게 수정하겠습니다!

2022-07-03 23:40 UTC, himJJong commented on src/main/resources/application-secret.yml
> -# Local settings
음.. 잘못 지워진것 같습니다 다시 되돌려 놓겠습니다!!😭

2022-07-04 02:32 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +//                .y_cord(restaurant.getY_cord())
넵! 다른 분들 코드를 보니 camelCase로 되어있네요!  
수정하도록 하겠습니다

2022-07-04 02:45 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/response/MenuInfoResponseDto.java
> +    private List menuList;
저도 확인했습니다!
MenuList의 경우 아래와 같이 나오는데
```json
    "menuList": [
        {
            "price": "10,800",
            "recommend": false,
            "menu": "텍사스칠리와퍼 세트",
            "desc": "비프칠리로 만나는 정통 와퍼",
            "img": "https://mud-kage.kakaocdn.net/dn/Ufvff/btrFKaQqctp/QTKB395xrYNO2uNrV1zsqK/img.png"
        },
        {
            "price": "9,700",
            "recommend": false,
            "menu": "텍사스칠리치킨버거 세트",
            "desc": "비프칠리로 만나는 치킨버거",
            "img": "https://mud-kage.kakaocdn.net/dn/cxbWvS/btrFP1ErjYC/jb6rt9gBh5DdD2wJArDW3K/img.png"
        },
       ..
```  
price, recommend, menu, desc, img에 대해서 menu만 필수적으로 나오고 나머지 필들에 대해서는 나올 때도 있고 안나올 때도 있어서 저렇게 두었습니다. 하지만 권장되는 방식이 아닌 만큼 수정하도록 하겠습니다!

2022-07-09 10:55 UTC, Yong-ga-ri commented
수정사항 반영해서 다시 push해 뒀습니다!
아직 Generic 타입에 대한 이해가 부족하여 가능한 선에서 작업을 완료하였습니다

2022-07-11 01:16 UTC, litsynp approved these changes
고생하셨습니다! 변수 이름 추천과 약간 우려되는 점 리뷰했습니다. 😃

2022-07-11 01:16 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/controller/RestaurantController.java
> +        MenuInfoResponseDto menuInfoResponseDto = menuService.restauRants(cid);
메소드명은 `getRestaurant`, `getRestaurantByCid` 등 액션을 포함하는 것이 더 적합할 것 같아요!

2022-07-11 01:16 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +                .xcoorDinate(Long.parseLong(jsonObject.getAsString("xcoorDinate")))
x와 coordinate가 각각의 단어니 `xCoordinate`가 더 적합할 것 같아요!

2022-07-11 01:16 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +                .xcoorDinate(Long.parseLong(jsonObject.getAsString("xcoorDinate")))
`jsonObject.getAsString` 부분이 받아온 데이터라서 이것도 바뀌게 된다면 잘 동작하지 않을 것 같은데 확인 부탁드려요!

2022-07-11 05:25 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +                .xcoorDinate(Long.parseLong(jsonObject.getAsString("xcoorDinate")))
넵 알겠습니다!! 리뷰 감사드립니다ㅎ

2022-07-16 10:33 UTC, merged