리뷰 API 테스트 코드
techeer-f5/jmt-monster-backend pull request #80
Opened 2022-07-03 13:19 UTC by Sith-call

## DONE
* 리뷰 API 테스트 코드 작성 완료

2022-07-03 13:38 UTC, litsynp requested changes
고생하셨습니다! 리뷰 확인 부탁드립니다 😀

그리고 `ReviewRequest` 라고 네이밍 된 부분이 있던데, `Review`와 다른 건가요?

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +                .ok()
리뷰를 생성한 뒤 보내는 응답이기 때문에 `201 CREATED`가 더 적합할 것 같은데 `200 OK`로 바꾸신 이유가 있나요?

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +    @GetMapping("/{id}") // Review ID로 조회
Review ID로 조회하는 것이 자명하기에 없어도 주석이 빠져도 좋을 것 같습니다!

더 명확하게 하고 싶으시다면 PathVariable 매개변수 부분에서 변수 이름을 `reviewId` 로 지정하셔도 좋을 것 같습니다.

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +    @PutMapping
Update할 때에는 ID가 PathVariable로 들어가는 것이 일반적인데 빼신 이유가 있나요?

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    private Review review;
Image를 M:N으로 연결하는 방법도 있는 점 알려드립니다! 🙂

지금은 Review에만 이미지를 달 수 있어서 이미지가 리뷰에 종속돼있지만, 관계 테이블을 중간에 추가해서
`Review` - `ReviewImage` - `UploadedImage`
이런 식으로 하면 이미지를 `Review` 뿐 아니라 다른 곳에도 달 수 있습니다!

(적용하라는 말씀을 드리는 것은 아닙니다!)

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        Review request_entity = reviewRepository.save(Review.builder()
변수 네이밍은 `camelCase` 적용이 좋을 것 같습니다!

2022-07-03 13:38 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        return reviewRepository.findByUserId(userId, pageable);
이 부분 `Review` 엔티티 관계 때문에 N+1 문제 발생 소지가 있을 것 같은데, 쿼리 로그 한번 보시는 게 좋을 것 같습니다.

발생한다면 fetch join (Querydsl JPA 등) 적용하면 좋을 것 같습니다.

2022-07-03 13:58 UTC, DPS0340 approved these changes
퀄리티, 노력 대단하시네요 👍
고생 많으셨습니다!!
Approve 하며 궁금한 부분 코멘트로 올려드립니다!

2022-07-03 13:58 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +                reviewRequestService.deleteRequestById(UUID.randomUUID());
when & then으로 한 블록으로 잡아주시면 좋을 것 같습니다!

2022-07-03 13:58 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +            assertThrows(ResourceNotFoundException.class,()->{
이쪽도 when과 then을 합쳐주시면 좋을 것 같습니다!

2022-07-03 13:58 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +    // 시간 관계상 Repository Test Code 작성하지 않아 Mocking도 하지 않음.
저는 QueryDSL 사용 메소드만 레포지토리 테스트를 작성했는데요, 레포지토리 메소드 쿼리는 추가적으로 커스터마이징하지 않은 이상 테스트는 굳이 작성하지 않으셔도 될 것 같은데 어떻게 생각하세요? 🤔

2022-07-03 13:58 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +    // 시간 관계상 Repository Test Code 작성하지 않아 Mocking도 하지 않음.
논의가 끝나면 추후 개발 컨벤션을 정할 때 참고할 수 있을 것 같습니다!

2022-07-03 13:58 UTC, DPS0340 commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestControllerTest.java
> +            mockMvc.perform(put("/api/v1/reviews")
이쪽도 when & then을 합쳐주시면 좋을 것 같습니다!

2022-07-03 13:58 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    }
@ToString Lombok 어노테이션을 사용하시면 조금 더 빠르게 구현이 가능할 것 같습니다!
갈아엎으시지는 않으셔도 돼요... ㅎㅎ

2022-07-04 01:39 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +                .ok()
원래 ReviewRequest로 엔티티까지 이름 지었다가 이후에 Review로 변경하였는데, 추가적으로 이름 변경시키도록 하겠습니다. 그리고 상태 코드는 201이 더 적합해 보이네요. 수정하겠습니다!

2022-07-04 01:39 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +    @GetMapping("/{id}") // Review ID로 조회
넵 알겠습니다 !

2022-07-04 01:41 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +    @PutMapping
ReviewRequestUpdateRequestDto 안에 ReviewId가 포함되어 있어서 뺐습니다. 혹시 PathVariable로 들어가는게 더 좋은 구현일까요?

2022-07-04 01:42 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    private Review review;
오 좋은 정보 감사드립니다! 공부해놓도록 하겠습니다.

2022-07-04 01:43 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        Review request_entity = reviewRepository.save(Review.builder()
아 snake_case가 있었네요. 인지를 못하고 있었습니다. 수정하겠습니다.

2022-07-04 01:44 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        return reviewRepository.findByUserId(userId, pageable);
이 부분은 잘 모르는 부분이라 공부한 뒤에 수정하도록 하겠습니다 !

2022-07-04 01:44 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +                reviewRequestService.deleteRequestById(UUID.randomUUID());
넵 알겠습니다 !

2022-07-04 01:45 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +            assertThrows(ResourceNotFoundException.class,()->{
넵 알겠습니다 !

2022-07-04 01:53 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestServiceTest.java
> +    // 시간 관계상 Repository Test Code 작성하지 않아 Mocking도 하지 않음.
아하 사실 승준님 계실 때 그때도 같은 이야기 했었습니다. 근데 제가 무의식적으로 Repository 테스트 코드도 짜야 한다고 생각해서 저렇게 주석 단 것 같네요. 실제 레포지토리 테스트로는 인터페이스에 제가 따로 선언한 메소드만 테스트 진행하였습니다. 혹시 이 부분에서 잘못된게 있다면 바로 수정하겠습니다~!

2022-07-04 01:56 UTC, Sith-call commented on src/test/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestControllerTest.java
> +            mockMvc.perform(put("/api/v1/reviews")
넵 알겠습니다 !

2022-07-04 01:57 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    }
아하 좋은 정보 감사드립니다!

2022-07-04 02:44 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/controller/ReviewRequestController.java
> +    @PutMapping
보통 PUT 요청에는 URI 경로 뒤에 ID를 붙입니다!
[참고](https://restfulapi.net/rest-put-vs-post/)

2022-07-04 02:49 UTC, Sith-call commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    }
사실 @toString을 사용했다가 지운 것인데 memory issue가 존재한다고 인텔리제이에서 경고가 나왔었습니다. 그래서 지웠던것 같네요 !

2022-07-04 02:49 UTC, Yong-ga-ri commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        return reviewRepository.findByUserId(userId, pageable);
N:1 관계에서 ManyToOne 어노테이션에 fetch.LAZY 옵션이 N+1 문제를 해결해줄 수 있던거로 기억하네요!

2022-07-04 02:51 UTC, Yong-ga-ri commented
확인 완료했습니다! 테스트코드 관련해서 저도 해보고싶네요 작성해주신 코드 많이 참고하겠습니다 :)  
수고하셨습니다 !!

2022-07-04 02:51 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/service/ReviewRequestService.java
> +        return reviewRepository.findByUserId(userId, pageable);
네, 일단 LAZY로 설정해두시면 성능 개선의 여지가 생깁니다! :D

2022-07-04 02:54 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/review/domain/ReviewImage.java
> +    }
`@ToString`을 기본으로 사용하면 연관된 테이블까지 매핑이 되는데, A entity와 B entity가 있을 때 `@ToString`을 양쪽에 달고 각 Entity를 서로 양방향으로 매핑할 경우 무한으로 toString을 호출하게 되므로 StackOverflow가 발생합니다. [참고](https://sorjfkrh5078.tistory.com/310)

그래서 toString() 메서드를 직접 구현하시거나, `@ToString`으로 한다면 필요없는 필드는 `@ToString`에서 exclude 옵션에 넣어주시면 됩니다.

2022-07-04 14:54 UTC, Sith-call commented
## 변경사항
* 변수 네이밍 컨벤션 통일
* 리뷰 생성 응답 Status code 변경 (200 -> 201)
* 불필요한 주석 제거
* PUT API 변경 (PathVariable 추가)
* 테스트 코드 주석 변경

## N+1 문제 이슈
JPA Pagination에서 발생한 N+1 문제를 해결하는 상황에서 ~ToMany 관계가 있는 경우에는 batch size를 이용하라고 나와 있습니다.(특히 ~ToMany 관계가 2개 이상 있는 경우에는 Querydsl의 fetch join이 불가능합니다.) 그런데 이미 전역 설정으로 batch size를 100으로 해둔 상태에서도 여전히 N+1 문제가 발생하네요. 혹시나 해결 방법 아시는 분 계시면 공유 부탁드립니다.
[~ToMany 두 개 있는 경우의 참고 자료](https://jojoldu.tistory.com/457)
[테코블 JPA Pagination, 그리고 N + 1 문제](https://tecoble.techcourse.co.kr/post/2021-07-26-jpa-pageable/)
[하이버네이트 default-batch-fetch-size 가 안되는 현상](https://yjksw.github.io/jpa-default-batch-fetch-size-not-working/)

2022-07-04 15:28 UTC, litsynp approved these changes

2022-07-04 15:37 UTC, litsynp commented
@Sith-call
로그 찍어보셨을 때 어느 부분에서 N+1 문제가 발생하고 있나요?

혹시 Review를 조회할 때 User에 대해서 N+1이 일어나고 있다면 Fetch join을 적용하셔야 할 것 같습니다.

https://lion-king.tistory.com/53

2022-07-05 05:40 UTC, merged