맛집 데이터 수집 2nd
techeer-f5/jmt-monster-backend pull request #88
Opened 2022-07-09 10:55 UTC by Yong-ga-ri

수정사항 반영해서 다시 push해 뒀습니다!
아직 Generic 타입에 대한 이해가 부족하여 가능한 선에서 작업을 완료하였습니다

2022-07-10 10:35 UTC, DPS0340 approved these changes
좋은 듯 하여 Approve 드립니다! 코멘트 달아 두었습니다! 👍

2022-07-10 10:35 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/service/MenuList.java
> +    private List menu;
`List<Object>` 타입으로 변경 부탁드립니다!

2022-07-10 10:36 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +        MenuList MENULIST = restaurantMapper.toMenuList(listMenu);
변수명을 menuList로 바꿔주세요!

2022-07-10 10:36 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +                .fromUriString(url +cid)
띄어쓰기 부탁드립니다!

2022-07-10 10:38 UTC, DPS0340 reviewed
추가 코멘트 달아드립니다!

2022-07-10 10:38 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +                .fromUriString(url +cid)
띄어쓰기 부탁드립니다!

2022-07-10 10:38 UTC, DPS0340 commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/service/MenuService.java
> +        RestaurantInfo restaurantInfo = restaurantMapper.toInformation(cid, restaurantName, xCord, yCord, MENULIST);
네이밍 컨벤션에 맞지 않기 때문에 menuList2등으로 변경 부탁드립니다!

2022-07-11 01:23 UTC, litsynp approved these changes
고생하셨습니다! 😀 코드 리뷰 남깁니다.

2022-07-11 01:23 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/service/MenuList.java
> +    private List menu;
이렇게 진행하시게 되면 
```json
{
    "cid": 212412144,
    // ...
    "menuList": {
        "menu": [ ... ]
    }
}
```

이런식으로 불필요하게 `menuList` 안에 `menu`가 들어갈 텐데 그냥 `List< ... > menuList`를 `RestaurantResponseDto`에 넣는게 더 좋을 것 같습니다.

2022-07-11 01:27 UTC, Sith-call approved these changes
수고하셨습니다~!

2022-07-13 13:34 UTC, litsynp requested changes
고생하셨어요! 리뷰 확인 부탁드립니다.

2022-07-13 13:34 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/repository/RestaurantRepository.java
> +@Component
`@Component`는 빠져도 될 것 같습니다!

2022-07-13 13:35 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/service/MenuList.java
> +    private List<RestaurantResponseDto> menu;
https://github.com/techeer-f5/jmt-monster-backend/pull/88#discussion_r917480469

에서 말씀드린 것은 `MenuList` 클래스가 필요없을 것 같다는 의미였습니다!

2022-07-16 07:51 UTC, himJJong commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/service/MenuList.java
> +    private List<RestaurantResponseDto> menu;
제가 잘못이해했군요 넵 알겠습니다!!

2022-07-17 06:05 UTC, Yong-ga-ri commented
@DPS0340 @litsynp @Sith-call 수정해서 푸쉬해뒀습니다!  
컨플릭까지 해결했으니 이모지 달아주시면 머지하도록 하겠습니다 :)

2022-07-17 09:14 UTC, litsynp approved these changes
고생하셨습니다!

2022-07-17 09:14 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/mapper/RestaurantMapper.java
> +    public RestaurantInfo toInformation(Long cid, String restaurantName, Long x, Long y, ArrayList<String> listMenu) {
확장성을 생각하면 `ArrayList` -> `List`가 더 좋을 것 같습니다!

2022-07-17 09:14 UTC, litsynp commented on src/main/java/com/techeer/f5/jmtmonster/domain/restaurant/dto/service/RestaurantInfo.java
> +    private ArrayList<String> menuList;
`ArrayList` -> `List`

같은 이유입니다!

2022-07-17 09:29 UTC, merged